version: '3'
services:
  postgres:
    image: "postgres:12"
    network_mode: bridge
    container_name: postgres
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ads_stats
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5431:5432

  scala-app:
    image: ads-stats-app:latest
    network_mode: bridge
    container_name: ads-stats-app
    expose:
      - 8000
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "jaegar-all-in-one:5775"]
    links:
      - postgres
  
  jaegar:
    image: jaegertracing/all-in-one:latest
    network_mode: bridge
    container_name: jaegar-all-in-one
    environment: 
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

volumes:
    postgres-data: