version: '3'
services:
  postgres:
    image: "postgres:12"
    network_mode: bridge
    container_name: postgres
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ads_stats
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5431:5432

  jaegar:
    image: jaegertracing/all-in-one:latest
    network_mode: bridge
    container_name: jaegar
    environment: 
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    expose:
      - 5775
      - 6831
      - 6832
      - 5778
      - 16686
      - 14268
      - 14250
      - 9411
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  ads-stats-app:
    image: ads-stats-app:latest
    network_mode: bridge
    container_name: ads-stats-app
    expose:
      - 8000
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres
      - jaegar
    command: ["./wait-for-it.sh", "postgres:5432", "jaegar:5775", "jaegar:16686"]
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8000/ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    links:
      - postgres
      - jaegar
  perf-test:
    image: perf-test-app:latest
    network_mode: bridge
    container_name: perf-test
    depends_on: 
      - ads-stats-app
    command: ["./wait-for-server.sh", "ads-stats-app", "8000", "java", "-Dis_time_travel_mode=false", "-Ddelivery_to_query_ratio=${delivery_to_query_ratio}", "-Ddelivery_to_click_ratio=${delivery_to_click_ratio}", "-Dclick_to_install_ratio=${click_to_install_ratio}", "-Drunning_time_in_seconds=${running_time_in_seconds}", "-jar", "app.jar"]
    links:
      - ads-stats-app
volumes:
    postgres-data: